export const ERROR_MESSAGES = {
    500: 'Error de Servidor Intentalo de nuevo mas tarde',
    404: 'No se encontro la pagina',
    403: 'No tienes permisos para acceder a esta pagina',
    401: 'No estas autorizado para acceder a esta pagina',
    400: 'Error en la solicitud',
    MENU_ALREADY_EXISTS: 'El Nombre del menu ya existe',
    MENU_NOT_FOUND: 'El menu no fue encontrado',
    MENU_NOT_UPDATED: 'El menu no fue actualizado',
    MENU_NOT_DELETED: 'El menu no fue eliminado',
    CATEGORY_ALREADY_EXISTS: 'La categoria ya existe',
    CATEGORY_NOT_FOUND: 'La categoria no fue encontrada',
    CATEGORY_NOT_UPDATED: 'La categoria no fue actualizada',
    CATEGORY_NOT_DELETED: 'La categoria no fue eliminada',
    CATEGORY_NOT_ADDED: 'La categoria no fue agregada',
    PRODUCT_ALREADY_EXISTS: 'El producto ya existe',
    PRODUCT_NOT_FOUND: 'El producto no fue encontrado',
    PRODUCT_NOT_UPDATED: 'El producto no fue actualizado',
    PRODUCT_NOT_DELETED: 'El producto no fue eliminado',
    PRODUCT_NOT_ADDED: 'El producto no fue agregado',
};

export const PRIVATE_ROUTES = [
    '/admin',
    '/dashboard',
    '/api/dashboard',
    '/api/payment/create-order',
];


export const MENU_NAMES_PROHIBITED = [
    'admin',
    'dashboard',
    'api',
    'login',
    'logout',
    'register',
    '404',
    '500',
    'favicon.ico',
    'robots.txt',
    'auth',
    'index',
    'home',
    'about',
    'contact',
    'services',
    'singin',
    'terms',
    'privacy',
    'payment',
    'pay',
    'checkout',
    'policy',
    'page',
    'astro',
    'inicio',
    'nosotros',
    'contacto',
    'servicios',
    'iniciar-sesion',
    'terminos',
    'es',
    'ar',
    'en',
    'porn',
    'xxx',
    'hentai',
    'hot',
    'menu',
    'snapmenu',
    'drug',
    'cp',
    'jp',
    'png',
    'jpg',
    'jpeg',
    'gif',
    'svg',
    'css',
    'js',
    'ts',
    'json',
    'xml',
    'webp',
    'webm',
    'mp4',
    'pdf',
    'drugs',
    'robot',
    "robots",
    "robots.txt",
    "init",
    ".env",
    "favicon",
    "demo",
    'medicine',
    'administrador',
    'assets',
    'favicon',
    'test',
    'aws',
    'google',
    'droga',
    'html',
    'webhook',
    "sitemap",
]